# Generated by Django 2.2.7 on 2019-11-09 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=40)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anijung.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=20)),
                ('court', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=20)),
                ('round', models.CharField(max_length=20)),
                ('result', models.TextField()),
                ('source', models.URLField(null=True)),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='anijung.Case')),
                ('judge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='anijung.Judge')),
            ],
        ),
    ]
