# Generated by Django 2.2.10 on 2020-03-07 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anijung', '0002_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anijung.Case'),
        ),
    ]
