# Generated by Django 2.2.10 on 2020-03-07 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anijung', '0003_auto_20200307_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='case',
        ),
        migrations.AddField(
            model_name='quote',
            name='decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anijung.Decision'),
        ),
    ]
